### PR TITLE
Update Python and Django Support

### PR DESCRIPTION
**Pull request by mfonism**
This PR drops EOLed Python and Django versions from Pinax Blog.

**IMPORTANT**
Django 3 is not yet added to the support matrix for this app because a dependency, Pinax Images, does not currently support Django 3.

Thankfully, there's a PR to fix that at https://github.com/pinax/pinax-images/pull/28

When that is fixed, and a Django 3 supporting version of the dependency is available on PyPI, Django 3 support can be added to this app.

When all of this is done, issue https://github.com/pinax/pinax-blog/issues/128 will be fixed.

### CODE REVIEW

**Comment by KatherineMichel** [comment]
Problem with pytz... Screen Shot 2020-05-03 at 10 31 13 PM

**Comment by KatherineMichel** [comment]
Closes #128 
Closes #130

**Comment by jonathan-s** [comment]
Thanks for making this PR. I've read through it and approve (for what it's worth).

**Comment by KatherineMichel** [comment]
@jonathan-s Thank you for approving!

**Pull request merged**
